"""Case Reporter Agent (plan §9.8) — T2 `synthesize_case`.

Assembles the final `CasePacket`. The LLM's `output_schema` is deliberately
narrow (`CaseNarrative`: prose only) — CLAUDE.md hard rule 1 means
`signals`/citations/`legal_status_per_match` must be echoed from
already-computed data, not regenerated by the model. Everything but the
narrative is assembled in plain Python from the `GraphFindings`/
`EnforcementFindings`/`CounterEvidence` dicts the caller already has.

Check order in `synthesize()`, and why it's this order: banned vocabulary
first (a content violation is worth surfacing before spending a retry cycle
on a citation problem), then numeric grounding, then citation validation.
Each failure is a distinct `SpecterError` subtype; none catches another's
exception (CLAUDE.md hard rule 7 — no fallback that masks a failure).
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import structlog
from neo4j import Driver

from specter.agents._base import AgentRuntime, build_agent, run_agent
from specter.agents._grounding import numeric_violations
from specter.core.banned_vocabulary import find_banned_phrases
from specter.core.contracts import (
    CaseLegalStatus,
    CaseNarrative,
    CasePacket,
    CounterEvidence,
    EvidenceBundle,
    RiskSignal,
)
from specter.core.errors import SpecterError
from specter.tools.evidence_tools import validate_citations

logger = structlog.get_logger(__name__)

AGENT_NAME = "case_reporter"
TASK_CLASS = "synthesize_case"
INSTRUCTION_FILE = "case_reporter.md"

_TASK_INSTRUCTION = (
    "Write the case narrative from the evidence below, in the controlled "
    "vocabulary your role brief describes — never a banned word. "
    "exhibited_indicators_summary must echo signal_count exactly, phrased as "
    '"exhibits N independently observed indicators". Do not compute, round, '
    "or invent any number yourself."
)


class BannedVocabularyError(SpecterError):
    """The narrative used a banned phrase (CLAUDE.md hard rule 9) — a regex
    post-check, not just an instruction.
    """


class NumericGroundingError(SpecterError):
    """A number in the narrative never appeared anywhere in the evidence
    bundle this call was given (CLAUDE.md hard rule 1).
    """


class UnresolvedCitationError(SpecterError):
    """A `source_ids` entry collected off `signals`/enforcement matches
    doesn't resolve to a stored artifact or an existing graph node
    (CLAUDE.md hard rule 3).
    """


def build_evidence(
    npi: str,
    graph_findings: dict[str, Any],
    enforcement_findings: dict[str, Any],
    counter_evidence: dict[str, Any],
) -> EvidenceBundle:
    signals = graph_findings.get("signals", [])
    evidence = {
        "fired_signals": signals,
        "signal_count": len(signals),
        "narration": graph_findings.get("narration"),
        "community_context": graph_findings.get("community_context"),
        "enforcement_matches": enforcement_findings.get("matches", []),
        "legal_status_per_match": enforcement_findings.get("legal_status_per_match", []),
        "counter_evidence": counter_evidence,
    }
    return EvidenceBundle(provider_npi=npi, evidence=evidence, task_instruction=_TASK_INSTRUCTION)


def _collect_source_ids(
    graph_findings: dict[str, Any], enforcement_findings: dict[str, Any]
) -> list[str]:
    from_signals = {
        source_id
        for signal in graph_findings.get("signals", [])
        for source_id in signal["source_ids"]
    }
    from_enforcement = {
        f"graph:enforcement_case:{case_id}" for case_id in enforcement_findings.get("matches", [])
    }
    return sorted(from_signals | from_enforcement)


async def synthesize(
    npi: str,
    graph_findings: dict[str, Any],
    enforcement_findings: dict[str, Any],
    counter_evidence: dict[str, Any],
    driver: Driver,
    evidence_dir: Path,
    runtime: AgentRuntime,
) -> CasePacket:
    agent = build_agent(
        name=AGENT_NAME,
        task_class=TASK_CLASS,
        instruction_file=INSTRUCTION_FILE,
        tools=[],
        output_schema=CaseNarrative,
        runtime=runtime,
    )
    evidence = build_evidence(npi, graph_findings, enforcement_findings, counter_evidence)
    logger.info("case_reporter.synthesizing", npi=npi)
    result = await run_agent(agent, TASK_CLASS, evidence, runtime, CaseNarrative)

    narrative_text = str(result.output["narrative"])
    indicators_summary = str(result.output["exhibited_indicators_summary"])
    full_narrative = f"{narrative_text}\n\n{indicators_summary}"

    banned = find_banned_phrases(full_narrative)
    if banned:
        raise BannedVocabularyError(f"{npi}: narrative used banned phrase(s) {banned}")

    violations = numeric_violations([narrative_text, indicators_summary], evidence.evidence)
    if violations:
        raise NumericGroundingError(f"{npi}: narrative cites ungrounded numbers {violations}")

    citation_report = validate_citations(
        _collect_source_ids(graph_findings, enforcement_findings), driver, evidence_dir
    )
    if not citation_report.all_resolved:
        raise UnresolvedCitationError(
            f"{npi}: unresolved source_ids {citation_report.unresolved_source_ids}"
        )

    return CasePacket(
        provider_npi=npi,
        narrative=full_narrative,
        signals=[RiskSignal(**signal) for signal in graph_findings.get("signals", [])],
        enforcement_matches=list(enforcement_findings.get("matches", [])),
        legal_status_per_match=[
            CaseLegalStatus(**match)
            for match in enforcement_findings.get("legal_status_per_match", [])
        ],
        counter_evidence=CounterEvidence(**counter_evidence),
        citation_report=citation_report,
        created_at=datetime.now(UTC),
    )
