"""CLAUDE.md Amendment 2 mitigation 2's required test (M9): no field/string
containing "gpt"/"agent"/"tier"/"model" survives `blind_case`. Offline, no
Neo4j/LLM needed.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from specter.core.contracts import CasePacket
from specter.judge.blind import ProvenanceLeakError, blind_case

_REPO_ROOT = Path(__file__).resolve().parent.parent


def _real_case() -> CasePacket:
    path = _REPO_ROOT / "data" / "cases" / "1003001439.json"
    return CasePacket.model_validate(json.loads(path.read_text()))


def test_blind_case_passes_a_real_clean_case() -> None:
    blinded = blind_case(_real_case())
    assert blinded.provider_npi == "1003001439"
    assert blinded.narrative == _real_case().narrative


def test_blind_case_raises_on_leaked_agent_substring() -> None:
    case = _real_case()
    case.narrative = "the agent observed a shared address cluster"
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_raises_on_leaked_model_substring() -> None:
    case = _real_case()
    case.narrative = "this finding was generated by the gpt-5.4 model"
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_raises_on_leaked_tier_substring() -> None:
    case = _real_case()
    case.narrative = "escalated to a higher tier for review"
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_is_case_insensitive() -> None:
    case = _real_case()
    case.narrative = "This case was reviewed by an AGENT twice."
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)
