"""CLAUDE.md Amendment 2 mitigation 2's required test (M9): no field/string
containing "gpt"/"agent"/"tier"/"model" survives `blind_case`. Offline, no
Neo4j/LLM needed.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from specter.core.contracts import CasePacket
from specter.judge.blind import ProvenanceLeakError, blind_case

_REPO_ROOT = Path(__file__).resolve().parent.parent


def _real_case() -> CasePacket:
    path = _REPO_ROOT / "data" / "cases" / "1003001439.json"
    return CasePacket.model_validate(json.loads(path.read_text()))


def test_blind_case_passes_a_real_clean_case() -> None:
    blinded = blind_case(_real_case())
    assert blinded.provider_npi == "1003001439"
    assert blinded.narrative == _real_case().narrative


def test_blind_case_raises_on_leaked_agent_substring() -> None:
    case = _real_case()
    case.narrative = "the agent observed a shared address cluster"
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_raises_on_leaked_model_substring() -> None:
    case = _real_case()
    case.narrative = "this finding was generated by the gpt-5.4 model"
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_raises_on_leaked_tier_substring() -> None:
    case = _real_case()
    case.narrative = "escalated to a higher tier for review"
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_is_case_insensitive() -> None:
    case = _real_case()
    case.narrative = "This case was reviewed by an AGENT twice."
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_allows_registered_agent_domain_vocabulary() -> None:
    # M9 live finding: the Skeptic's own reasoning legitimately used
    # "registered-agent style address" (shell-company investigation
    # vocabulary) on the very first real judge run — this must not raise.
    case = _real_case()
    case.narrative = (
        "The address matches a registered-agent style address commonly used "
        "by shell entities, and a registered agent alone is not proof of fraud."
    )
    blinded = blind_case(case)
    assert "registered" in blinded.narrative.lower()


def test_blind_case_still_catches_a_leak_next_to_benign_vocabulary() -> None:
    case = _real_case()
    case.narrative = (
        "This is a registered-agent address. Separately, the agent observed a "
        "shared address cluster."
    )
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)


def test_blind_case_allows_billing_agents_domain_vocabulary() -> None:
    # M9 live finding: "shared phone numbers can appear in ... billing
    # agents" was a real Skeptic benign-explanation on the second live run.
    case = _real_case()
    case.narrative = "Shared phone numbers can appear in billing agents or answering services."
    blinded = blind_case(case)
    assert "billing" in blinded.narrative.lower()


def test_blind_case_allows_business_model_and_provider_tier_vocabulary() -> None:
    case = _real_case()
    case.narrative = (
        "This is consistent with a normal business model and a standard "
        "provider tier structure, not an anomaly."
    )
    blinded = blind_case(case)
    assert "business model" in blinded.narrative.lower()


def test_blind_case_still_catches_bare_model_and_tier_leaks() -> None:
    case = _real_case()
    case.narrative = "The model produced this output directly."
    with pytest.raises(ProvenanceLeakError):
        blind_case(case)
    case2 = _real_case()
    case2.narrative = "This was scored at a higher tier than usual."
    with pytest.raises(ProvenanceLeakError):
        blind_case(case2)
